[Service]
Environment=VLLM_DSV4_NVCOMP_FP8_DIR=/opt/lvllmds4-x/sm89-tuning/nvcomp-test/compressed
Environment=VLLM_DSV4_NVCOMP_BRIDGE=/opt/lvllmds4-x/sm89-tuning/nvcomp-test/libnvcomp_torch_bridge.so
Environment=VLLM_DSV4_NVCOMP_MOE_TIMING=1
