import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { basename, dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path";

const CACHE_METADATA_FILE = ".agent-k-cmake-cache.json";
const IGNORED_DIRECTORIES = new Set([
  ".cache",
  ".git",
  ".hg",
  ".idea",
  ".svn",
  ".vscode",
  "build",
  "node_modules",
  "out",
]);

export type CMakeConfigurationSnapshot = {
  fingerprint: string;
  newestInputMtimeMs: number;
};

export type PreparedCompilationDatabase = {
  commands: string;
  excluded: number;
  included: number;
};

function isIgnoredDirectory(name: string): boolean {
  const normalized = name.toLocaleLowerCase("en-US");
  return IGNORED_DIRECTORIES.has(normalized) || normalized.startsWith("cmake-build-");
}

function isCMakeInput(name: string): boolean {
  const normalized = name.toLocaleLowerCase("en-US");
  return normalized === "cmakelists.txt"
    || normalized === "cmakepresets.json"
    || normalized === "cmakeuserpresets.json"
    || extname(normalized) === ".cmake";
}

export function isCMakeConfigurationPath(root: string, path: string): boolean {
  const projectPath = relative(root, path);
  if (
    isAbsolute(projectPath) ||
    projectPath === ".." ||
    projectPath.startsWith(`..${sep}`)
  ) return false;
  const parts = projectPath.split(/[\\/]/);
  const name = parts.pop();
  return Boolean(name) && !parts.some(isIgnoredDirectory) && isCMakeInput(name!);
}

async function configurationInputs(root: string, directory = root): Promise<string[]> {
  const inputs: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) continue;
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      if (!isIgnoredDirectory(entry.name)) inputs.push(...await configurationInputs(root, path));
      continue;
    }
    if (entry.isFile() && isCMakeInput(entry.name)) inputs.push(path);
  }
  return inputs;
}

/** Captures only project-owned CMake configuration. Generated build trees and
 * fetched dependencies are excluded so their own timestamps never invalidate
 * a reusable compilation database. */
export async function cmakeConfigurationSnapshot(root: string): Promise<CMakeConfigurationSnapshot> {
  const inputs = (await configurationInputs(root)).sort((left, right) =>
    relative(root, left).localeCompare(relative(root, right), "en-US"));
  const hash = createHash("sha256");
  let newestInputMtimeMs = 0;
  for (const path of inputs) {
    const [contents, metadata] = await Promise.all([readFile(path), stat(path)]);
    newestInputMtimeMs = Math.max(newestInputMtimeMs, metadata.mtimeMs);
    hash.update(relative(root, path).replaceAll("\\", "/"));
    hash.update("\0");
    hash.update(contents);
    hash.update("\0");
  }
  return { fingerprint: hash.digest("hex"), newestInputMtimeMs };
}

async function freshCompilationDatabase(
  candidates: readonly string[],
  snapshot: CMakeConfigurationSnapshot,
): Promise<string | undefined> {
  const databases = await Promise.all(candidates.filter(existsSync).map(async (path) => ({
    modifiedAt: (await stat(path)).mtimeMs,
    path,
  })));
  return databases
    .filter((database) => database.modifiedAt >= snapshot.newestInputMtimeMs)
    .sort((left, right) => right.modifiedAt - left.modifiedAt)[0]?.path;
}

/** Finds a user-managed compilation database without walking arbitrary build
 * output. These locations cover CMake's conventional single-config layouts. */
export async function findProjectCompilationDatabase(
  root: string,
  snapshot: CMakeConfigurationSnapshot,
): Promise<string | undefined> {
  const candidates = [
    join(root, "compile_commands.json"),
    join(root, "build", "compile_commands.json"),
    join(root, "out", "build", "compile_commands.json"),
  ];
  for (const entry of await readdir(root, { withFileTypes: true })) {
    if (entry.isDirectory() && entry.name.toLocaleLowerCase("en-US").startsWith("cmake-build-"))
      candidates.push(join(root, entry.name, "compile_commands.json"));
  }
  return freshCompilationDatabase(candidates, snapshot);
}

export async function cachedCompilationDatabase(
  buildDirectory: string,
  snapshot: CMakeConfigurationSnapshot,
): Promise<string | undefined> {
  const commands = join(buildDirectory, "compile_commands.json");
  if (!existsSync(commands)) return undefined;
  try {
    const metadata = JSON.parse(await readFile(join(buildDirectory, CACHE_METADATA_FILE), "utf8")) as {
      fingerprint?: unknown;
      version?: unknown;
    };
    return metadata.version === 1 && metadata.fingerprint === snapshot.fingerprint
      ? commands
      : undefined;
  } catch {
    // Adopt caches generated by Agent K versions predating the fingerprint
    // file only when the compilation database is newer than every CMake input.
    return freshCompilationDatabase([commands], snapshot);
  }
}

export async function recordCompilationDatabase(
  commands: string,
  snapshot: CMakeConfigurationSnapshot,
): Promise<void> {
  await writeFile(join(dirname(commands), CACHE_METADATA_FILE), `${JSON.stringify({
    fingerprint: snapshot.fingerprint,
    version: 1,
  }, undefined, 2)}\n`, "utf8");
}

function projectTranslationUnit(root: string, commandsDirectory: string, entry: unknown): boolean {
  if (!entry || typeof entry !== "object") return false;
  const value = entry as { directory?: unknown; file?: unknown };
  if (typeof value.file !== "string") return false;
  const directory = typeof value.directory === "string" ? value.directory : commandsDirectory;
  const file = isAbsolute(value.file) ? resolve(value.file) : resolve(directory, value.file);
  const projectRelative = relative(root, file);
  if (isAbsolute(projectRelative) || projectRelative === ".." || projectRelative.startsWith(`..${sep}`)) return false;
  return !projectRelative.split(/[\\/]/u).includes("_deps");
}

/** Copies a compilation database into Agent K's fast private cache and omits
 * FetchContent translation units. Command working directories and arguments
 * remain untouched, so generated headers and project build outputs still work
 * while clangd stores its persistent index beside this private database. */
export async function prepareClangdCompilationDatabase(
  root: string,
  sourceCommands: string,
  targetDirectory: string,
): Promise<PreparedCompilationDatabase> {
  const source = await readFile(sourceCommands, "utf8");
  const parsed = JSON.parse(source) as unknown;
  if (!Array.isArray(parsed)) throw new Error("compile_commands.json must contain an array");
  const projectEntries = parsed.filter((entry) => projectTranslationUnit(root, dirname(sourceCommands), entry));
  const entries = projectEntries.length ? projectEntries : parsed;
  const excluded = projectEntries.length ? parsed.length - projectEntries.length : 0;
  const output = `${JSON.stringify(entries, undefined, 2)}\n`;
  const commands = join(targetDirectory, "compile_commands.json");
  await mkdir(targetDirectory, { recursive: true });
  if (await readFile(commands, "utf8").catch(() => "") !== output)
    await writeFile(commands, output, "utf8");
  return { commands, excluded, included: entries.length };
}

export function describeCompilationDatabase(root: string, commands: string): string {
  const directory = dirname(commands);
  const label = directory === root ? basename(commands) : relative(root, directory).replaceAll("\\", "/");
  return label && !label.startsWith("..") ? label : "Agent K cache";
}
